# Generated by Django 4.2.30 on 2026-06-15 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField(db_column='id_paciente', unique=True)),
                ('nombres', models.CharField(db_column='nombres', max_length=150)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=150)),
                ('edad', models.IntegerField(db_column='edad')),
                ('sexo', models.CharField(db_column='sexo', max_length=20)),
                ('peso', models.FloatField(db_column='peso')),
                ('altura', models.FloatField(db_column='altura')),
                ('IMC', models.FloatField(db_column='IMC')),
                ('presion_sistolica', models.IntegerField(db_column='presión_sistólica')),
                ('presion_diastolica', models.IntegerField(db_column='presión_diastólica')),
                ('frecuencia_cardiaca', models.IntegerField(db_column='frecuencia_cardiaca')),
                ('glucosa', models.FloatField(db_column='glucosa')),
                ('colesterol', models.FloatField(db_column='colesterol')),
                ('saturacion_oxigeno', models.FloatField(db_column='saturación_oxígeno')),
                ('temperatura', models.FloatField(db_column='temperatura')),
                ('antecedentes_familiares', models.BooleanField(db_column='antecedentes_familiares')),
                ('fumador', models.BooleanField(db_column='fumador')),
                ('consumo_alcohol', models.BooleanField(db_column='consumo_alcohol')),
                ('actividad_fisica', models.CharField(db_column='actividad_física', max_length=100)),
                ('diagnostico_preliminar', models.CharField(db_column='diagnóstico_preliminar', max_length=250)),
                ('riesgo_enfermedad', models.CharField(db_column='riesgo_enfermedad', max_length=50)),
                ('fecha_consulta', models.DateField(db_column='fecha_consulta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registros_procesados', models.IntegerField()),
                ('registros_limpios', models.IntegerField()),
                ('duplicados_eliminados', models.IntegerField()),
                ('tiempo_ejecucion', models.FloatField()),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], max_length=20)),
                ('errores', models.TextField(blank=True, null=True)),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_etl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
